version: '3.8'
services:
  backend:
    container_name: backend
    environment:
      - MONGO_ADDRESS=database
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=test
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - '4000:4000'
    networks:
      - bdx-quizz
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules

  mongodb:
    image: mongo
    container_name: database
    ports:
      - 27018:27017
    networks:
      - bdx-quizz

networks:
  bdx-quizz:
    driver: bridge
